# Generated by Django 3.1.5 on 2021-01-29 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=10, unique=True)),
                ('userPwd', models.CharField(max_length=32)),
                ('registerTime', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=10)),
                ('userState', models.IntegerField(default=0)),
                ('tipInfo', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': '用户名1',
                'verbose_name_plural': '用户名2',
                'ordering': ['-registerTime'],
            },
        ),
    ]
