# Generated by Django 3.1.5 on 2021-01-29 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-registerTime'], 'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
    ]
