# Generated by Django 3.1.5 on 2021-01-31 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20210131_1241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='confirm',
            old_name='code',
            new_name='registerCode',
        ),
    ]
